In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available  Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand
torch.rand(2,3)

tensor([[0.7660, 0.8864, 0.2955],
        [0.3247, 0.6284, 0.0147]])

In [11]:
#using rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [12]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# other ways
print("using arange->", torch.arange(0,10,2))
print("using linspace->", torch.linspace(0,10,2))
print("using eye->", torch.eye(5))
print("Using full->", torch.full((3,3),5))

using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0., 10.])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [17]:
# Tensors Shape
x= torch.tensor([[1,2,3],[4,5,6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.full_like((x),2)

tensor([[2, 2, 2],
        [2, 2, 2]])

# Tensor Data Types

In [24]:
# find data type
x.dtype

torch.int64

In [28]:
#  assign data type
y = torch.tensor([[1.0,2.0,3.0]],dtype=torch.int32)

In [30]:
# using to
y.to(torch.uint8)

tensor([[1, 2, 3]], dtype=torch.uint8)

# Mathematical Operations

In [31]:
# 1. Scalar Operation
# addition
print(x+2)
# subtraction
print(x-2)
# multiplication
print(x*2)
#divison
print(x/2)
# int divison
print(x*100)//3
# mod
print(x%2)
# power
print(X**2)

tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[-1,  0,  1],
        [ 2,  3,  4]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[100, 200, 300],
        [400, 500, 600]])


TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

# Element Wise Operation

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])
tensor([[-0.4491, -0.7447, -0.2103],
        [-0.7834, -0.8752, -0.0209]])
tensor([[0.1870, 0.0337, 0.0870],
        [0.1064, 0.1213, 0.5565]])
tensor([[0.3691, 0.0544, 0.4973],
        [0.1309, 0.1221, 0.9724]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [35]:
c = torch.tensor([[-1,-2,-3]])

In [36]:
torch.abs(c)

tensor([[1, 2, 3]])

In [37]:
torch.neg(x)

tensor([[-1, -2, -3],
        [-4, -5, -6]])

In [38]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [39]:
# round
torch.round(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [40]:
torch.ceil(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [42]:
torch.floor(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
torch.clamp(x, min=2, max =3)

tensor([[2, 2, 3],
        [3, 3, 3]])

# Reduction Operation

In [45]:
# sum
torch.sum(x)

tensor(21)

In [46]:
# sum along columns
torch.sum(x,dim=0)

tensor([5, 7, 9])

In [47]:
torch.sum(x,dim=1)

tensor([ 6, 15])

In [51]:
# mean
torch.mean(x.to(torch.float32))

tensor(3.5000)

In [52]:
torch.mean(x.to(torch.float32),dim=0)

tensor([2.5000, 3.5000, 4.5000])

In [53]:
torch.mean(x.to(torch.float32),dim=1)


tensor([2., 5.])

In [54]:
torch.median(x)

tensor(3)

In [55]:
torch.max(x)

tensor(6)

In [56]:
torch.min(x)

tensor(1)

In [57]:
# product
torch.prod(x)

tensor(720)

In [58]:
torch.std(x)

RuntimeError: std and var only support floating point and complex dtypes

In [60]:
torch.std(x.to(torch.float32))

tensor(1.8708)

In [61]:
torch.var(x.to(torch.float32))

tensor(3.5000)

In [62]:
torch.argmin(x)

tensor(0)

In [64]:
torch.argmax(x)

tensor(5)

# Matrix Operations

In [ ]:
torch.dot(mat1,mat2)
torch.transpose(mat)
torch.det(mat) # determinant
torch.inverse(mat)

# Special function

In [65]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [67]:
torch.exp(x)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [68]:
torch.sqrt(x)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

In [69]:
torch.sigmoid(x)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975]])

In [72]:
torch.softmax(x.to(torch.float32),dim=0)

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])

In [73]:
torch.relu(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

# Inplace Operation -> permanent inplace

In [74]:
a.add_(b)
a.relu_()

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])

In [75]:
y = x

In [76]:
x[0][0] =0

In [77]:
x

tensor([[0, 2, 3],
        [4, 5, 6]])

In [78]:
y

tensor([[0, 2, 3],
        [4, 5, 6]])

In [79]:
# changes replicate in y also


In [80]:
id(a)

140644352984176

In [81]:
id(b)

140643856359568

In [82]:
z = x.clone()

In [83]:
x[0][0] = 1

In [84]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [85]:
z

tensor([[0, 2, 3],
        [4, 5, 6]])

In [86]:
id(x)

140644353126576

In [87]:
id(z)

140643852469840

# Tensor Operations on GPU

In [88]:
torch.cuda.is_available()

True

In [89]:
device = torch.device('cuda')

In [90]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [91]:
# moving an existing tensor on GPU
a = torch.rand(2,3)

In [92]:
a

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [95]:
b = a.to(device=device)

In [97]:
# GPU tensor will perform operations on GPU
# make speed faster of execution

# Reshaping Tensors

In [98]:
a = torch.ones(4,4)

In [100]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [101]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
import torch

# In PyTorch, torch.permute() is a function that returns a view of the original tensor with its dimensions rearranged according to a specified order.

# Create a 3D tensor
x = torch.randn(2, 3, 4)
print("Original tensor shape:", x.shape) # Output: Original tensor shape: torch.Size([2, 3, 4])

# Permute the dimensions from (0, 1, 2) to (2, 0, 1)
y = x.permute(2, 0, 1)
print("Permuted tensor shape:", y.shape) # Output: Permuted tensor shape: torch.Size([4, 2, 3])

Original tensor shape: torch.Size([2, 3, 4])
Permuted tensor shape: torch.Size([4, 2, 3])


In [103]:
# unsqueeze
# In PyTorch, torch.unsqueeze() is a function used to add a new dimension of size one at a specified position within a tensor's shape.
c = torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [104]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [107]:
c.unsqueeze_(3).shape # inplace func

torch.Size([226, 226, 3, 1])

In [109]:
# squeeze
# In PyTorch, torch.squeeze() is a function used to remove dimensions of size 1 from a tensor's shape.
c.squeeze(3).shape

torch.Size([226, 226, 3])

# Numpy and Pytorch

In [110]:
import numpy as np

In [111]:
a = torch.tensor([1,2,3])

In [112]:
b = a.numpy()

In [113]:
c = np.array([[1,2,3]])

In [114]:
c

array([[1, 2, 3]])

In [115]:
torch.from_numpy(c)

tensor([[1, 2, 3]])